Feature/option buttons
Derwin1310/Pokeapi pull request #7
Opened 2022-04-21 04:06 UTC by Derwin1310

2022-04-21 04:13 UTC, padronjosef requested changes

2022-04-21 04:13 UTC, padronjosef commented on src/components/context/index.js
> +        // console.log("🚀 ~ file: index.js ~ line 29 ~ getPokemons ~ pokemonFullData", pokemonFullData)
borra el console.log

2022-04-21 04:13 UTC, padronjosef commented on src/components/paginationBar/index.js
> +	const actualPage = Math.ceil(pageNumbers / 10) + 1;
esto pasalo a unos helpets

2022-04-21 04:18 UTC, Derwin1310 commented on src/components/context/index.js
> +        // console.log("🚀 ~ file: index.js ~ line 29 ~ getPokemons ~ pokemonFullData", pokemonFullData)
done

2022-04-21 05:27 UTC, Derwin1310 commented on src/components/paginationBar/index.js
> +	const actualPage = Math.ceil(pageNumbers / 10) + 1;
done

2022-04-23 02:13 UTC, padronjosef approved these changes

2022-04-23 02:14 UTC, merged