feature/searcher 01: implementing the functions for the search bar
Derwin1310/Pokeapi pull request #9
Opened 2022-04-25 06:01 UTC by Derwin1310

2022-04-25 06:06 UTC, padronjosef requested changes

2022-04-25 06:06 UTC, padronjosef commented on src/components/pokemonsList/pokemonNotFound.js
> +		<section className='error'>
esto no es un error, cambia el nombre de las clases a not-found, not-found__wrapper, etc...

2022-04-25 06:06 UTC, padronjosef commented on src/components/context/index.js
> +		const query = searchValue.toLowerCase().trim().replaceAll(' ', '-');
ese .toLowerCase().trim().replaceAll(' ', '-')

ponlo en un helper, te va a hacer falta en otros lugares,

tambien crea otro para revertirlo.

2022-04-25 06:06 UTC, padronjosef commented on src/components/pokemonsList/pokemonStats.js
> +					name.replaceAll('-', ' '),
para el helper que te dije arriba.

2022-04-26 16:14 UTC, Derwin1310 commented on src/components/pokemonsList/pokemonNotFound.js
> +		<section className='error'>
done

2022-04-26 16:31 UTC, Derwin1310 commented on src/components/context/index.js
> +		const query = searchValue.toLowerCase().trim().replaceAll(' ', '-');
done

2022-04-26 16:38 UTC, Derwin1310 commented on src/components/pokemonsList/pokemonStats.js
> +					name.replaceAll('-', ' '),
done

2022-04-28 00:14 UTC, padronjosef approved these changes

2022-04-28 00:15 UTC, merged